# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/server/worker/pipeline/transform/transform.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python_pachyderm.proto.pfs import pfs_pb2 as src_dot_pfs_dot_pfs__pb2
from python_pachyderm.proto.server.worker.datum import datum_pb2 as src_dot_server_dot_worker_dot_datum_dot_datum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/server/worker/pipeline/transform/transform.proto',
  package='pachyderm.worker.pipeline.transform',
  syntax='proto3',
  serialized_options=b'ZFgithub.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform',
  serialized_pb=b'\n4src/server/worker/pipeline/transform/transform.proto\x12#pachyderm.worker.pipeline.transform\x1a\x11src/pfs/pfs.proto\x1a#src/server/worker/datum/datum.proto\"\x8f\x01\n\x08\x44\x61tumSet\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ile_set\x18\x02 \x01(\t\x12\"\n\routput_commit\x18\x03 \x01(\x0b\x32\x0b.pfs.Commit\x12 \n\x0bmeta_commit\x18\x04 \x01(\x0b\x32\x0b.pfs.Commit\x12\x1b\n\x05stats\x18\x05 \x01(\x0b\x32\x0c.datum.StatsBHZFgithub.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transformb\x06proto3'
  ,
  dependencies=[src_dot_pfs_dot_pfs__pb2.DESCRIPTOR,src_dot_server_dot_worker_dot_datum_dot_datum__pb2.DESCRIPTOR,])




_DATUMSET = _descriptor.Descriptor(
  name='DatumSet',
  full_name='pachyderm.worker.pipeline.transform.DatumSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='pachyderm.worker.pipeline.transform.DatumSet.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_set', full_name='pachyderm.worker.pipeline.transform.DatumSet.file_set', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_commit', full_name='pachyderm.worker.pipeline.transform.DatumSet.output_commit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta_commit', full_name='pachyderm.worker.pipeline.transform.DatumSet.meta_commit', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats', full_name='pachyderm.worker.pipeline.transform.DatumSet.stats', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=293,
)

_DATUMSET.fields_by_name['output_commit'].message_type = src_dot_pfs_dot_pfs__pb2._COMMIT
_DATUMSET.fields_by_name['meta_commit'].message_type = src_dot_pfs_dot_pfs__pb2._COMMIT
_DATUMSET.fields_by_name['stats'].message_type = src_dot_server_dot_worker_dot_datum_dot_datum__pb2._STATS
DESCRIPTOR.message_types_by_name['DatumSet'] = _DATUMSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatumSet = _reflection.GeneratedProtocolMessageType('DatumSet', (_message.Message,), {
  'DESCRIPTOR' : _DATUMSET,
  '__module__' : 'src.server.worker.pipeline.transform.transform_pb2'
  # @@protoc_insertion_point(class_scope:pachyderm.worker.pipeline.transform.DatumSet)
  })
_sym_db.RegisterMessage(DatumSet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
