# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from python_pachyderm.proto.v2.admin import admin_pb2 as python__pachyderm_dot_proto_dot_v2_dot_admin_dot_admin__pb2


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InspectCluster = channel.unary_unary(
                '/admin_v2.API/InspectCluster',
                request_serializer=python__pachyderm_dot_proto_dot_v2_dot_admin_dot_admin__pb2.InspectClusterRequest.SerializeToString,
                response_deserializer=python__pachyderm_dot_proto_dot_v2_dot_admin_dot_admin__pb2.ClusterInfo.FromString,
                )


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InspectCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InspectCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectCluster,
                    request_deserializer=python__pachyderm_dot_proto_dot_v2_dot_admin_dot_admin__pb2.InspectClusterRequest.FromString,
                    response_serializer=python__pachyderm_dot_proto_dot_v2_dot_admin_dot_admin__pb2.ClusterInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin_v2.API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InspectCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin_v2.API/InspectCluster',
            python__pachyderm_dot_proto_dot_v2_dot_admin_dot_admin__pb2.InspectClusterRequest.SerializeToString,
            python__pachyderm_dot_proto_dot_v2_dot_admin_dot_admin__pb2.ClusterInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
