# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: python_pachyderm/proto/v2/task/task.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


class State(betterproto.Enum):
    UNKNOWN = 0
    RUNNING = 1
    SUCCESS = 2
    FAILURE = 3
    CLAIMED = 4


@dataclass(eq=False, repr=False)
class Group(betterproto.Message):
    namespace: str = betterproto.string_field(1)
    group: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class TaskInfo(betterproto.Message):
    id: str = betterproto.string_field(1)
    group: "Group" = betterproto.message_field(2)
    state: "State" = betterproto.enum_field(3)
    reason: str = betterproto.string_field(4)
    input_type: str = betterproto.string_field(5)
    input_data: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class ListTaskRequest(betterproto.Message):
    group: "Group" = betterproto.message_field(1)
