# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/deploy/deploy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client/deploy/deploy.proto',
  package='deploy',
  syntax='proto3',
  serialized_options=_b('Z0github.com/pachyderm/pachyderm/src/client/deploy'),
  serialized_pb=_b('\n\x1a\x63lient/deploy/deploy.proto\x12\x06\x64\x65ploy\"\x8e\x01\n\x1a\x44\x65ployStorageSecretRequest\x12@\n\x07secrets\x18\x01 \x03(\x0b\x32/.deploy.DeployStorageSecretRequest.SecretsEntry\x1a.\n\x0cSecretsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\x1d\n\x1b\x44\x65ployStorageSecretResponse2g\n\x03\x41PI\x12`\n\x13\x44\x65ployStorageSecret\x12\".deploy.DeployStorageSecretRequest\x1a#.deploy.DeployStorageSecretResponse\"\x00\x42\x32Z0github.com/pachyderm/pachyderm/src/client/deployb\x06proto3')
)




_DEPLOYSTORAGESECRETREQUEST_SECRETSENTRY = _descriptor.Descriptor(
  name='SecretsEntry',
  full_name='deploy.DeployStorageSecretRequest.SecretsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='deploy.DeployStorageSecretRequest.SecretsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='deploy.DeployStorageSecretRequest.SecretsEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=181,
)

_DEPLOYSTORAGESECRETREQUEST = _descriptor.Descriptor(
  name='DeployStorageSecretRequest',
  full_name='deploy.DeployStorageSecretRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secrets', full_name='deploy.DeployStorageSecretRequest.secrets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEPLOYSTORAGESECRETREQUEST_SECRETSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=181,
)


_DEPLOYSTORAGESECRETRESPONSE = _descriptor.Descriptor(
  name='DeployStorageSecretResponse',
  full_name='deploy.DeployStorageSecretResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=212,
)

_DEPLOYSTORAGESECRETREQUEST_SECRETSENTRY.containing_type = _DEPLOYSTORAGESECRETREQUEST
_DEPLOYSTORAGESECRETREQUEST.fields_by_name['secrets'].message_type = _DEPLOYSTORAGESECRETREQUEST_SECRETSENTRY
DESCRIPTOR.message_types_by_name['DeployStorageSecretRequest'] = _DEPLOYSTORAGESECRETREQUEST
DESCRIPTOR.message_types_by_name['DeployStorageSecretResponse'] = _DEPLOYSTORAGESECRETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeployStorageSecretRequest = _reflection.GeneratedProtocolMessageType('DeployStorageSecretRequest', (_message.Message,), dict(

  SecretsEntry = _reflection.GeneratedProtocolMessageType('SecretsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DEPLOYSTORAGESECRETREQUEST_SECRETSENTRY,
    __module__ = 'client.deploy.deploy_pb2'
    # @@protoc_insertion_point(class_scope:deploy.DeployStorageSecretRequest.SecretsEntry)
    ))
  ,
  DESCRIPTOR = _DEPLOYSTORAGESECRETREQUEST,
  __module__ = 'client.deploy.deploy_pb2'
  # @@protoc_insertion_point(class_scope:deploy.DeployStorageSecretRequest)
  ))
_sym_db.RegisterMessage(DeployStorageSecretRequest)
_sym_db.RegisterMessage(DeployStorageSecretRequest.SecretsEntry)

DeployStorageSecretResponse = _reflection.GeneratedProtocolMessageType('DeployStorageSecretResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYSTORAGESECRETRESPONSE,
  __module__ = 'client.deploy.deploy_pb2'
  # @@protoc_insertion_point(class_scope:deploy.DeployStorageSecretResponse)
  ))
_sym_db.RegisterMessage(DeployStorageSecretResponse)


DESCRIPTOR._options = None
_DEPLOYSTORAGESECRETREQUEST_SECRETSENTRY._options = None

_API = _descriptor.ServiceDescriptor(
  name='API',
  full_name='deploy.API',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=214,
  serialized_end=317,
  methods=[
  _descriptor.MethodDescriptor(
    name='DeployStorageSecret',
    full_name='deploy.API.DeployStorageSecret',
    index=0,
    containing_service=None,
    input_type=_DEPLOYSTORAGESECRETREQUEST,
    output_type=_DEPLOYSTORAGESECRETRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['API'] = _API

# @@protoc_insertion_point(module_scope)
