#!/bin/bash
set -e

# will extract from stdin and to ./proto/pachyderm/src
tar xf /dev/stdin

# VERSION matches the MajorVersion of pachyderm
OUTDIR="python_pachyderm/proto/v${VERSION}"

mkdir -p ${OUTDIR}
mv ./proto/pachyderm/src/* ${OUTDIR}

# Remove protobuf extensions, that are Go specific.
for i in $(find ${OUTDIR} -name "*.proto"); do
    # remove gogoproto
    sed -i 's/import.*gogo.proto.*\;//' "${i}"
    sed -i 's/\[.*gogoproto.*\]//' "${i}"
    sed -i 's/.*gogoproto.*//' "${i}"

    # remove the protoextensions/log.proto
    sed -i 's/import.*protoextensions\/log.proto.*\;//' ${i}
    sed -i 's/\[.*log.*\]//' ${i}
done

# fix imports to be relative to OUTDIR
for i in $(find ${OUTDIR} -name "*.proto"); do
    perl -pi -e "s/import \"((?!google).*)\"/import \"python_pachyderm\/proto\/v${VERSION}\/\$1\"/" ${i}
done

# generate protobuf and gRPC code from proto files
# should result in {}_pb2.py and {}_pb2_grpc.py per proto
find ${OUTDIR} -name '*.proto' | xargs python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=.

# Clean up
find ${OUTDIR} -name '*.proto' | xargs rm
find ${OUTDIR} -type d -exec touch {}/__init__.py \;

tar cf - ${OUTDIR}
